const products = [
  {name:"Soundcore R60i NC",brand:"Soundcore",price:6499,cat:"earbuds",icon:"🎧"},
  {name:"Soundcore K20i",brand:"Soundcore",price:2499,cat:"earbuds",icon:"🎧"},
  {name:"Soundcore P41i",brand:"Soundcore",price:8499,cat:"earbuds",icon:"🎧"},
  {name:"Soundcore Liberty 5",brand:"Soundcore",price:17499,cat:"earbuds",icon:"🎧"},
  {name:"Soundcore P30i",brand:"Soundcore",price:6499,cat:"earbuds",icon:"🎧"},
  {name:"Soundcore Liberty 4NC",brand:"Soundcore",price:14999,cat:"earbuds",icon:"🎧"},
  {name:"Soundcore R50i NC",brand:"Soundcore",price:6499,cat:"earbuds",icon:"🎧"},
  {name:"Soundcore Liberty 4 Pro",brand:"Soundcore",price:19999,cat:"earbuds",icon:"🎧"},
  {name:"Soundcore P20i",brand:"Soundcore",price:3999,cat:"earbuds",icon:"🎧"},
  {name:"Soundcore Life U2i",brand:"Soundcore",price:2999,cat:"earbuds",icon:"🎧"},
  {name:"Soundcore Q30",brand:"Soundcore",price:12999,cat:"headphones",icon:"🎧"},
  {name:"Soundcore Q20i",brand:"Soundcore",price:9999,cat:"headphones",icon:"🎧"},
  {name:"Soundcore Q11i",brand:"Soundcore",price:4499,cat:"headphones",icon:"🎧"},
  {name:"Soundcore Space 1",brand:"Soundcore",price:17999,cat:"headphones",icon:"🎧"},
  {name:"Soundcore Space 1 Pro",brand:"Soundcore",price:25499,cat:"headphones",icon:"🎧"},
  {name:"Soundcore Space Q45",brand:"Soundcore",price:19999,cat:"headphones",icon:"🎧"},
  {name:"Soundcore Boom 3i",brand:"Soundcore",price:11999,cat:"speakers",icon:"🔊"},
  {name:"Soundcore Rave 3S",brand:"Soundcore",price:39999,cat:"speakers",icon:"🔊"},
  {name:"Soundcore Boom 2 Plus",brand:"Soundcore",price:31999,cat:"speakers",icon:"🔊"},
  {name:"Soundcore Select 4 Go",brand:"Soundcore",price:3499,cat:"speakers",icon:"🔊"},
  {name:"Soundcore Select 3",brand:"Soundcore",price:6499,cat:"speakers",icon:"🔊"},
  {name:"Soundcore X500",brand:"Soundcore",price:28999,cat:"speakers",icon:"🔊"},
  {name:"Anker PowerConf S330",brand:"Anker",price:8499,cat:"accessories",icon:"🎙️"},
  {name:"Anker Nylon USB-C to USB-A 2.0 Cable 10FT",brand:"Anker",price:599,cat:"cables",icon:"🔌"},
  {name:"Anker Zolo USB-A to USB-C Cable (3.3ft)",brand:"Anker",price:999,cat:"cables",icon:"🔌"},
  {name:"Anker 322 USB-C to USB-C Cable (3ft Braided)",brand:"Anker",price:999,cat:"cables",icon:"🔌"},
  {name:"Anker 322 USB-C to Lightning Cable (3ft Braided)",brand:"Anker",price:2999,cat:"cables",icon:"🔌"},
  {name:"Anker USB-C to USB-C Cable (3ft, 240W)",brand:"Anker",price:1999,cat:"cables",icon:"🔌"},
  {name:"Anker PowerLine +II USB-C to USB-C Cable",brand:"Anker",price:1899,cat:"cables",icon:"🔌"},
  {name:"Anker 543 USB-C to USB-C Cable (Bio-Based 3ft)",brand:"Anker",price:1499,cat:"cables",icon:"🔌"},
  {name:"Anker 543 USB-C to USB-C Cable (Bio-Based 6ft)",brand:"Anker",price:1899,cat:"cables",icon:"🔌"},
  {name:"Anker USB-C to HDMI Nylon Cable 6ft",brand:"Anker",price:3299,cat:"cables",icon:"🔌"},
  {name:"Anker 322 USB-C to USB-C Cable",brand:"Anker",price:1999,cat:"cables",icon:"🔌"},
  {name:"Anker 322 USB-C to USB-C Cable (6ft)",brand:"Anker",price:2199,cat:"cables",icon:"🔌"},
  {name:"Anker PowerLine III USB-C to USB-C 100W",brand:"Anker",price:2199,cat:"cables",icon:"🔌"},
  {name:"Anker 542 USB-C to Lightning Cable (Bio-Nylon 3ft)",brand:"Anker",price:2999,cat:"cables",icon:"🔌"},
  {name:"Anker 310 Lightning to USB-C (6FT)",brand:"Anker",price:3399,cat:"cables",icon:"🔌"},
  {name:"PowerWave 10 Station 1S2A",brand:"Anker",price:4199,cat:"chargers",icon:"⚡"},
  {name:"Anker 620 MagGo Phone Grip",brand:"Anker",price:2499,cat:"accessories",icon:"📱"},
  {name:"Anker 533 Magnetic Wireless Charger (3-in-1 Stand)",brand:"Anker",price:8609,cat:"chargers",icon:"⚡"},
  {name:"Anker 623 Magnetic Wireless Charger (MagGo)",brand:"Anker",price:8999,cat:"chargers",icon:"⚡"},
  {name:"Anker 321 MagGo Battery (Powercore 5k)",brand:"Anker",price:4999,cat:"powerbanks",icon:"🔋"},
  {name:"Anker 323 Car Charger (52.5W)",brand:"Anker",price:2499,cat:"chargers",icon:"⚡"},
  {name:"Anker PowerBank (25K, 165W)",brand:"Anker",price:13999,cat:"powerbanks",icon:"🔋"},
  {name:"Anker Prime 20000mAh Power Bank (200W)",brand:"Anker",price:17499,cat:"powerbanks",icon:"🔋"},
  {name:"Anker 323 Power Bank 10K",brand:"Anker",price:4499,cat:"powerbanks",icon:"🔋"},
  {name:"Anker 535 USB-C Hub (5-in-1, for iMac)",brand:"Anker",price:9499,cat:"accessories",icon:"🖥️"},
  {name:"Hi-Tune H5",brand:"UGreen",price:4499,cat:"earbuds",icon:"🎧"},
  {name:"UGreen HiTune P3",brand:"UGreen",price:3999,cat:"earbuds",icon:"🎧"},
  {name:"UGreen HiTune T3 Pro",brand:"UGreen",price:4999,cat:"earbuds",icon:"🎧"},
  {name:"UGreen HiTune Max5C",brand:"UGreen",price:6999,cat:"earbuds",icon:"🎧"},
  {name:"UGreen HiTune Max5 Hybrid ANC",brand:"UGreen",price:8999,cat:"earbuds",icon:"🎧"},
  {name:"UGreen Nexode 100W Desktop Charger",brand:"UGreen",price:8199,cat:"chargers",icon:"⚡"},
  {name:"UGreen GaN 200W Desktop Charger",brand:"UGreen",price:11499,cat:"chargers",icon:"⚡"},
  {name:"UGreen Nexode 300W 5-Port PD GaN Charger",brand:"UGreen",price:18999,cat:"chargers",icon:"⚡"},
  {name:"Nexode USB-C Fast Charger (30W)",brand:"UGreen",price:3999,cat:"chargers",icon:"⚡"},
  {name:"Nexode 30W USB-C PD",brand:"UGreen",price:4299,cat:"chargers",icon:"⚡"},
  {name:"Nexode RG USB-C (30W)",brand:"UGreen",price:4199,cat:"chargers",icon:"⚡"},
  {name:"UGreen Nexode 30W USB-C PD GaN",brand:"UGreen",price:4199,cat:"chargers",icon:"⚡"},
  {name:"UGreen 65W 3-Port PD GaN Charger",brand:"UGreen",price:6999,cat:"chargers",icon:"⚡"},
  {name:"UGreen Fast Charging Power Adapter PD 20W",brand:"UGreen",price:2999,cat:"chargers",icon:"⚡"},
  {name:"UGreen Nexode Pro 100W 3-Port GaN Charger",brand:"UGreen",price:8999,cat:"chargers",icon:"⚡"},
  {name:"UGreen Nexode 100W 4-Port PD GaN Charger",brand:"UGreen",price:8999,cat:"chargers",icon:"⚡"},
  {name:"UGreen 2-in-1 Magnetic Wireless Charger",brand:"UGreen",price:7999,cat:"chargers",icon:"⚡"},
  {name:"UGreen 20000mAh Two-way Fast Charging Power Bank",brand:"UGreen",price:9499,cat:"powerbanks",icon:"🔋"},
  {name:"UGreen 20000mAh 130W Fast Charging Power Bank",brand:"UGreen",price:9199,cat:"powerbanks",icon:"🔋"},
  {name:"UGreen 25000mAh 200W Fast Charging Power Bank",brand:"UGreen",price:12299,cat:"powerbanks",icon:"🔋"},
  {name:"UGreen 20000mAh Power Bank with Built-in Cable",brand:"UGreen",price:5499,cat:"powerbanks",icon:"🔋"},
  {name:"UGreen 5000mAh Power Bank with Built-in USB-C",brand:"UGreen",price:7299,cat:"powerbanks",icon:"🔋"},
  {name:"UGreen 12000mAh 100W Fast Charging Power Bank",brand:"UGreen",price:7499,cat:"powerbanks",icon:"🔋"},
  {name:"10000mAh Two-way Fast Charging Power Bank",brand:"UGreen",price:4999,cat:"powerbanks",icon:"🔋"},
  {name:"10000mAh Two-way Fast Charging Power Bank (30W)",brand:"UGreen",price:5699,cat:"powerbanks",icon:"🔋"},
  {name:"20000mAh Two-way Fast Charging Power Bank (100W)",brand:"UGreen",price:9499,cat:"powerbanks",icon:"🔋"},
  {name:"UGreen 10000mAh Magnetic Wireless Power Bank",brand:"UGreen",price:8499,cat:"powerbanks",icon:"🔋"},
  {name:"UGreen 5000mAh Power Bank with Built-in USB-C (22.5W)",brand:"UGreen",price:4999,cat:"powerbanks",icon:"🔋"},
  {name:"UGreen 25000mAh 145W Two-way Fast Charging Power Bank",brand:"UGreen",price:14999,cat:"powerbanks",icon:"🔋"},
  {name:"UGreen Uno USB-C to USB-C PD Cable (1m)",brand:"UGreen",price:1499,cat:"cables",icon:"🔌"},
  {name:"USB-A to Lightning Cable",brand:"UGreen",price:2199,cat:"cables",icon:"🔌"},
  {name:"USB-C to Lightning Cable (1m)",brand:"UGreen",price:2699,cat:"cables",icon:"🔌"},
  {name:"USB-C to Lightning Cable (M/M)",brand:"UGreen",price:2699,cat:"cables",icon:"🔌"},
  {name:"USB-C to USB-C PD Cable (100W)",brand:"UGreen",price:1099,cat:"cables",icon:"🔌"},
  {name:"UGreen USB-C to Lightning Cable (2m)",brand:"UGreen",price:2999,cat:"cables",icon:"🔌"},
];
